In [1]:
import numpy as np

In [ ]:
l1=[1,2,3]

v1=np.array([10,20,5])
v2=np.array([5,5,10])
print(v1*v2)
print(v1+v2)
print(v1.dot(v2))
print(v2)
#property function
print(v1.ndim)
#column vector
print(v1.shape)

[ 50 100  50]
[15 25 15]
200
[ 5  5 10]
1
(3,)


In [8]:
m1=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
print(m1)

m2=np.array([[10,20,30],
            [40,50,60],
            [70,80,90]])
print(m2)
print("============================")
print("========operation============")

print(m1*m2)

print(m1.dot(m2))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]
========operation============
[[ 10  40  90]
 [160 250 360]
 [490 640 810]]
[[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]


In [11]:
#function property
class student:
   def __init__(self,name):
      self.name=name
   @property
   def get_info(self):
      return f"my nameis {self.name}"



s1=student("mariam")
s1.get_info       

'my nameis mariam'

In [13]:
m1=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

print(m1.ndim)
print(m1.shape)

2
(3, 3)


In [ ]:
vec = np.array([1,2,3,4,5,6])
mat = vec.reshape((3,2))
print(mat)


# def reshape(x,y):




[[1 2]
 [3 4]
 [5 6]]


In [ ]:
vec = np.array([1,2,3,4])

vec.shape[0]

m1=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])



m1.shape[0]
m1.shape[1]


3

In [ ]:
#column vector
vec = np.array([1,2,3,4])
mat = vec.reshape(vec.shape[0],1)
mat

mat=vec[:, None]
mat



array([[1],
       [2],
       [3],
       [4]])

In [31]:
mat=np.array([[1,2,3],
       [4,"5",6],
       [7,8,9]])


mat.dtype
#priority of type
#object-->string-->float-->int-->bool
#dtype('int64')
#dtype('<U21')
#dtype('float64')


f_mat=mat.astype(float)
f_mat.dtype

dtype('float64')