In [1]:
!pip install nltk
import nltk  
nltk.download()
nltk.download('punkt')


[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [2]:
# tokenize the text into individual sentences
text = "Hello! How are you doing today? I hope you're having a good day."
sentences =nltk.sent_tokenize(text)
tokens =nltk.word_tokenize(text)
print(sentences)
print(tokens)

['Hello!', 'How are you doing today?', "I hope you're having a good day."]
['Hello', '!', 'How', 'are', 'you', 'doing', 'today', '?', 'I', 'hope', 'you', "'re", 'having', 'a', 'good', 'day', '.']


In [3]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [4]:
stopwords.words('arabic')

['إذ',
 'إذا',
 'إذما',
 'إذن',
 'أف',
 'أقل',
 'أكثر',
 'ألا',
 'إلا',
 'التي',
 'الذي',
 'الذين',
 'اللاتي',
 'اللائي',
 'اللتان',
 'اللتيا',
 'اللتين',
 'اللذان',
 'اللذين',
 'اللواتي',
 'إلى',
 'إليك',
 'إليكم',
 'إليكما',
 'إليكن',
 'أم',
 'أما',
 'أما',
 'إما',
 'أن',
 'إن',
 'إنا',
 'أنا',
 'أنت',
 'أنتم',
 'أنتما',
 'أنتن',
 'إنما',
 'إنه',
 'أنى',
 'أنى',
 'آه',
 'آها',
 'أو',
 'أولاء',
 'أولئك',
 'أوه',
 'آي',
 'أي',
 'أيها',
 'إي',
 'أين',
 'أين',
 'أينما',
 'إيه',
 'بخ',
 'بس',
 'بعد',
 'بعض',
 'بك',
 'بكم',
 'بكم',
 'بكما',
 'بكن',
 'بل',
 'بلى',
 'بما',
 'بماذا',
 'بمن',
 'بنا',
 'به',
 'بها',
 'بهم',
 'بهما',
 'بهن',
 'بي',
 'بين',
 'بيد',
 'تلك',
 'تلكم',
 'تلكما',
 'ته',
 'تي',
 'تين',
 'تينك',
 'ثم',
 'ثمة',
 'حاشا',
 'حبذا',
 'حتى',
 'حيث',
 'حيثما',
 'حين',
 'خلا',
 'دون',
 'ذا',
 'ذات',
 'ذاك',
 'ذان',
 'ذانك',
 'ذلك',
 'ذلكم',
 'ذلكما',
 'ذلكن',
 'ذه',
 'ذو',
 'ذوا',
 'ذواتا',
 'ذواتي',
 'ذي',
 'ذين',
 'ذينك',
 'ريث',
 'سوف',
 'سوى',
 'شتان',
 'عدا',
 'عسى',
 'عل'

In [5]:
arabic_text ="قامت الشركة بإصدار بيانات تفصيلية حول أدائها في الربع الأول من العام الحالي"
#tokenize the text into words
words = word_tokenize(arabic_text)
print(len(words))
print(words)

13
['قامت', 'الشركة', 'بإصدار', 'بيانات', 'تفصيلية', 'حول', 'أدائها', 'في', 'الربع', 'الأول', 'من', 'العام', 'الحالي']


In [6]:
#load arabic stop words
stop_words = set(stopwords.words('arabic'))
stop_words

{'ء',
 'ءَ',
 'آ',
 'آب',
 'آذار',
 'آض',
 'آمينَ',
 'آناء',
 'آنفا',
 'آه',
 'آها',
 'آهاً',
 'آهٍ',
 'آهِ',
 'آي',
 'أ',
 'أبدا',
 'أبريل',
 'أبو',
 'أبٌ',
 'أجل',
 'أجمع',
 'أحد',
 'أخبر',
 'أخذ',
 'أخو',
 'أخٌ',
 'أربع',
 'أربعاء',
 'أربعة',
 'أربعمئة',
 'أربعمائة',
 'أرى',
 'أسكن',
 'أصبح',
 'أصلا',
 'أضحى',
 'أطعم',
 'أعطى',
 'أعلم',
 'أغسطس',
 'أف',
 'أفريل',
 'أفعل به',
 'أفٍّ',
 'أقبل',
 'أقل',
 'أكتوبر',
 'أكثر',
 'أل',
 'ألا',
 'ألف',
 'ألفى',
 'أم',
 'أما',
 'أمام',
 'أمامك',
 'أمامكَ',
 'أمد',
 'أمس',
 'أمسى',
 'أمّا',
 'أن',
 'أنا',
 'أنبأ',
 'أنت',
 'أنتم',
 'أنتما',
 'أنتن',
 'أنتِ',
 'أنشأ',
 'أنى',
 'أنًّ',
 'أنّى',
 'أهلا',
 'أو',
 'أوت',
 'أوشك',
 'أول',
 'أولئك',
 'أولاء',
 'أولالك',
 'أوه',
 'أوّهْ',
 'أى',
 'أي',
 'أيا',
 'أيار',
 'أيضا',
 'أيلول',
 'أين',
 'أينما',
 'أيها',
 'أيّ',
 'أيّان',
 'أُفٍّ',
 'ؤ',
 'إحدى',
 'إذ',
 'إذا',
 'إذاً',
 'إذما',
 'إذن',
 'إزاء',
 'إلا',
 'إلى',
 'إليك',
 'إليكم',
 'إليكما',
 'إليكن',
 'إليكنّ',
 'إليكَ',
 'إلَيْكَ',
 'إلّا',


In [9]:
#filter out the stop words from the text
filtered_words = [words[i] for i in range(len(words)) if words[i] not in stop_words]
print(len(filtered_words))
print(filtered_words)

11
['قامت', 'الشركة', 'بإصدار', 'بيانات', 'تفصيلية', 'حول', 'أدائها', 'الربع', 'الأول', 'العام', 'الحالي']


In [10]:
filtered_text =' '.join(filtered_words)
print(filtered_text)

قامت الشركة بإصدار بيانات تفصيلية حول أدائها الربع الأول العام الحالي


In [11]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [12]:
english_text = "Hello, how are you doing? i hope you are doing well."
#tokenize the text into words
words = word_tokenize(english_text)
print(len(words))
print(words)


14
['Hello', ',', 'how', 'are', 'you', 'doing', '?', 'i', 'hope', 'you', 'are', 'doing', 'well', '.']


In [13]:
stop_words = set(stopwords.words('english'))

filtered_words = [word for word in words if not word in stop_words]
print(len(filtered_words))
print(filtered_words)

6
['Hello', ',', '?', 'hope', 'well', '.']


In [14]:
filtered_text = ' '.join(filtered_words)
print(filtered_text)

Hello , ? hope well .


In [15]:
#stemming
import nltk
from nltk.stem import PorterStemmer

In [ ]:
#return word into original
stemmer = PorterStemmer()
words = ["walking", "jumps", "jumped", "jumping"]
for word in words:
   stemmed_word = stemmer.stem(word)
   print(f"{word} -> {stemmed_word}")

walking -> walk
jumps -> jump
jumped -> jump
jumping -> jump


In [17]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [18]:
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.tokenize import word_tokenize

text = "The quick brown foxes jumped over the lazy dogs"

# Stemming
stemmer =PorterStemmer()
stemmed_word = [stemmer.stem(word) for word in word_tokenize(text)]
print(stemmed_word)

# Lemmatization
lemmatizer = WordNetLemmatizer()
lemmatizer_words = [lemmatizer.lemmatize(word) for word in word_tokenize(text) ]
print(lemmatizer_words)

['the', 'quick', 'brown', 'fox', 'jump', 'over', 'the', 'lazi', 'dog']
['The', 'quick', 'brown', 'fox', 'jumped', 'over', 'the', 'lazy', 'dog']


In [19]:
import re

text='''
Elon musk's phone number is 9991116666, call him if you have any questions on dodgecoin.
Tesla's revenue is 40 billion
Tesla's CFO number (999)-333-7777
'''

In [20]:
pattern = '\d{3}'
matches = re.findall(pattern,text)
matches

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\hp\AppData\Local\Temp\ipykernel_19188\2901638991.py:1: SyntaxWarning: invalid escape sequence '\d'
  pattern = '\d{3}'


['999', '111', '666', '999', '333', '777']

In [21]:
pattern = '\(\d{3}\)-\d{3}-\d{4}|\d{10}'
matches = re.findall(pattern,text)
matches

<>:1: SyntaxWarning: invalid escape sequence '\('
<>:1: SyntaxWarning: invalid escape sequence '\('
C:\Users\hp\AppData\Local\Temp\ipykernel_19188\1835809014.py:1: SyntaxWarning: invalid escape sequence '\('
  pattern = '\(\d{3}\)-\d{3}-\d{4}|\d{10}'


['9991116666', '(999)-333-7777']

In [24]:
text = '''
Note 1 - Overview
Tesla, Inc. (“Tesla”, the “Company”, “we”, “us” or “our”) was incorporated in the State of Delaware on July 1, 2003. We design, develop, manufacture and sell high-performance fully electric vehicles and design, manufacture, install and sell solar energy generation and energy storage
products. Our Chief Executive Officer, as the chief operating decision maker (“CODM”), organizes our company, manages resource allocations and measures performance among two operating and reportable segments: (i) automotive and (ii) energy generation and storage.
Beginning in the first quarter of 2021, there has been a trend in many parts of the world of increasing availability and administration of vaccines
against COVID-19, as well as an easing of restrictions on social, business, travel and government activities and functions. On the other hand, infection
rates and regulations continue to fluctuate in various regions and there are ongoing global impacts resulting from the pandemic, including challenges
and increases in costs for logistics and supply chains, such as increased port congestion, intermittent supplier delays and a shortfall of semiconductor
supply. We have also previously been affected by temporary manufacturing closures, employment and compensation adjustments and impediments to
administrative activities supporting our product deliveries and deployments.
Note 2 - Summary of Significant Accounting Policies
Unaudited Interim Financial Statements
The consolidated balance sheet as of September 30, 2021, the consolidated statements of operations, the consolidated statements of
comprehensive income, the consolidated statements of redeemable noncontrolling interests and equity for the three and nine months ended September
30, 2021 and 2020 and the consolidated statements of cash flows for the nine months ended September 30, 2021 and 2020, as well as other information
disclosed in the accompanying notes, are unaudited. The consolidated balance sheet as of December 31, 2020 was derived from the audited
consolidated financial statements as of that date. The interim consolidated financial statements and the accompanying notes should be read in
conjunction with the annual consolidated financial statements and the accompanying notes contained in our Annual Report on Form 10-K for the year
ended December 31, 2020.
'''

In [25]:
pattern  = 'Note.\d.-.[^\n]*'
matches = re.findall(pattern,text)
matches

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\hp\AppData\Local\Temp\ipykernel_19188\2651066637.py:1: SyntaxWarning: invalid escape sequence '\d'
  pattern  = 'Note.\d.-.[^\n]*'


['Note 1 - Overview', 'Note 2 - Summary of Significant Accounting Policies']

In [26]:
pattern = 'Note.\d.-.([^\n]*)'
matches = re.findall(pattern, text)
matches

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\hp\AppData\Local\Temp\ipykernel_19188\2132289705.py:1: SyntaxWarning: invalid escape sequence '\d'
  pattern = 'Note.\d.-.([^\n]*)'


['Overview', 'Summary of Significant Accounting Policies']

In [31]:
text = '''
The gross cost of operating lease vehicles in FY2021 Q1 was $4.85 billion.
In previous quarter i.e. fy2020 Q4 it was $3 billion fy2020 Q5.
'''
#['FY2021 Q1', 'fy2020 Q4']

In [34]:
pattern ='FY\d{4} Q[1-4]'
matches =re.findall(pattern,text,flags=re.IGNORECASE)
matches

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\hp\AppData\Local\Temp\ipykernel_19188\1247804541.py:1: SyntaxWarning: invalid escape sequence '\d'
  pattern ='FY\d{4} Q[1-4]'


['FY2021 Q1', 'fy2020 Q4']

In [42]:
text = '''
Tesla's gross cost of operating lease vehicles in FY2021 Q1 was $4.85 billion.
In previous quarter i.e. FY2020 Q4 it was $3 billion.
'''
# ( $4.85 , $3)
pattern ='\$[\d(.\d)+]+'
matches =re.findall(pattern,text,flags=re.IGNORECASE)
matches

<>:6: SyntaxWarning: invalid escape sequence '\$'
<>:6: SyntaxWarning: invalid escape sequence '\$'
C:\Users\hp\AppData\Local\Temp\ipykernel_19188\56183731.py:6: SyntaxWarning: invalid escape sequence '\$'
  pattern ='\$[\d(.\d)+]+'


['$4.85', '$3']

In [43]:
import re
text='my name is ali and my salary : 10000'
pattern ='salary.:.([0-9]+)'
print(re.findall(pattern, text))
print(re.sub(pattern,'20000',text))

['10000']
my name is ali and my 20000


In [44]:
import spacy


In [46]:
nlp =spacy.load('en_core_web_sm')
text = "knbmvnb,mvncb,mncvm,b"
doc = nlp("Elon flew to mars yesterday. He carried biryani masala with him")
for token in doc:
   print(token,"||",token.pos_,"||",spacy.explain(token.pos_),"\n")

Elon || PROPN || proper noun 

flew || VERB || verb 

to || ADP || adposition 

mars || NOUN || noun 

yesterday || NOUN || noun 

. || PUNCT || punctuation 

He || PRON || pronoun 

carried || VERB || verb 

biryani || ADJ || adjective 

masala || NOUN || noun 

with || ADP || adposition 

him || PRON || pronoun 



In [47]:
doc = nlp("Wow! Dr. Strange made 265 million $ on the very first day")
for token in doc :
   print(token,"  | ",token.pos_," | ",spacy.explain(token.pos_)," | ",token.tag_," | ",spacy.explain(token.tag_),"\n")

Wow   |  INTJ  |  interjection  |  UH  |  interjection 

!   |  PUNCT  |  punctuation  |  .  |  punctuation mark, sentence closer 

Dr.   |  PROPN  |  proper noun  |  NNP  |  noun, proper singular 

Strange   |  PROPN  |  proper noun  |  NNP  |  noun, proper singular 

made   |  VERB  |  verb  |  VBD  |  verb, past tense 

265   |  NUM  |  numeral  |  CD  |  cardinal number 

million   |  NUM  |  numeral  |  CD  |  cardinal number 

$   |  NUM  |  numeral  |  CD  |  cardinal number 

on   |  ADP  |  adposition  |  IN  |  conjunction, subordinating or preposition 

the   |  DET  |  determiner  |  DT  |  determiner 

very   |  ADV  |  adverb  |  RB  |  adverb 

first   |  ADJ  |  adjective  |  JJ  |  adjective (English), other noun-modifier (Chinese) 

day   |  NOUN  |  noun  |  NN  |  noun, singular or mass 



In [48]:
earnings_text="""Microsoft Corp. today announced the following results for the quarter ended December 31, 2021, as compared to the corresponding period of last fiscal year:

·         Revenue was $51.7 billion and increased 20%
·         Operating income was $22.2 billion and increased 24%
·         Net income was $18.8 billion and increased 21%
·         Diluted earnings per share was $2.48 and increased 22%
“Digital technology is the most malleable resource at the world’s disposal to overcome constraints and reimagine everyday work and life,” said Satya Nadella, chairman and chief executive officer of Microsoft. “As tech as a percentage of global GDP continues to increase, we are innovating and investing across diverse and growing markets, with a common underlying technology stack and an operating model that reinforces a common strategy, culture, and sense of purpose.”
“Solid commercial execution, represented by strong bookings growth driven by long-term Azure commitments, increased Microsoft Cloud revenue to $22.1 billion, up 32% year over year” said Amy Hood, executive vice president and chief financial officer of Microsoft."""

doc= nlp(earnings_text)

filtered_tokens =[]
for token in doc :
    if token.pos_ not in ["SPACE", "PUNCT", "X"]:
        filtered_tokens.append(token)


In [52]:
filtered_tokens[:10]

[Microsoft,
 Corp.,
 today,
 announced,
 the,
 following,
 results,
 for,
 the,
 quarter]

In [53]:
count = doc.count_by(spacy.attrs.POS)
count

{96: 15,
 92: 45,
 100: 23,
 90: 9,
 85: 16,
 93: 16,
 97: 27,
 98: 1,
 84: 20,
 103: 10,
 87: 6,
 99: 5,
 89: 12,
 86: 3,
 94: 3,
 95: 2}

In [54]:
doc.vocab[96].text

'PROPN'

In [55]:
count.items()

dict_items([(96, 15), (92, 45), (100, 23), (90, 9), (85, 16), (93, 16), (97, 27), (98, 1), (84, 20), (103, 10), (87, 6), (99, 5), (89, 12), (86, 3), (94, 3), (95, 2)])

In [56]:
for k,v in count.items():
   print(doc.vocab[k].text,"|",v)

PROPN | 15
NOUN | 45
VERB | 23
DET | 9
ADP | 16
NUM | 16
PUNCT | 27
SCONJ | 1
ADJ | 20
SPACE | 10
AUX | 6
SYM | 5
CCONJ | 12
ADV | 3
PART | 3
PRON | 2


In [57]:
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

text = "The quick brown fox jumps over the lazy dog."

word = nltk.word_tokenize(text)
pos_tags = nltk.pos_tag(words)
for word,tag in pos_tags:
   print(word,tag)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


walking VBG
jumps NNS
jumped VBD
jumping VBG


In [58]:
import spacy
nlp = spacy.load("en_core_web_sm")

In [59]:
nlp.pipe_names


['tok2vec', 'tagger', 'parser', 'attribute_ruler', 'lemmatizer', 'ner']

In [60]:
doc = nlp("Tesla Inc is going to acquire twitter for $45 billion")
for ent in doc.ents:
   print(ent.text," | ",ent.label_," | ",spacy.explain(ent.label_))

Tesla Inc  |  ORG  |  Companies, agencies, institutions, etc.
$45 billion  |  MONEY  |  Monetary values, including unit


In [61]:
from spacy import displacy
displacy.render(doc,style="ent")

In [62]:
nlp.pipe_labels['ner']

['CARDINAL',
 'DATE',
 'EVENT',
 'FAC',
 'GPE',
 'LANGUAGE',
 'LAW',
 'LOC',
 'MONEY',
 'NORP',
 'ORDINAL',
 'ORG',
 'PERCENT',
 'PERSON',
 'PRODUCT',
 'QUANTITY',
 'TIME',
 'WORK_OF_ART']

In [63]:
doc = nlp("Tesla Inc is going to acquire Twitter Inc for $45 billion")
for ent in doc.ents:
   print(ent.text," | ",ent.label_," | ",ent.start_char,"|",ent.end_char)

Tesla Inc  |  ORG  |  0 | 9
Twitter Inc  |  PERSON  |  30 | 41
$45 billion  |  MONEY  |  46 | 57


In [64]:
s = doc[2:5]
s

is going to

In [65]:
type(s)

spacy.tokens.span.Span

In [66]:
from spacy.tokens import Span
s1 = Span(doc,0,1,label='ORG')
s2 = Span(doc,5,6,label='ORG')
doc.set_ents([s1,s2],default="unmodified")

In [67]:
for ent in doc.ents:
   print(ent.text," | ",ent.label_)

Tesla Inc  |  ORG
acquire  |  ORG
Twitter Inc  |  PERSON
$45 billion  |  MONEY


In [68]:
import nltk
#This model is a pre-trained classifier that identifies named entities (such as people, organizations, locations, etc.) in text.
nltk.download('maxent_ne_chunker')
nltk.download('words')
from nltk import word_tokenize, pos_tag, ne_chunk
input_text = "Steve Jobs was the CEO of Apple Corp. in California."
tokens = word_tokenize(input_text)
pos_tags = pos_tag(tokens)
print(pos_tags)
ne_tree = ne_chunk(pos_tags)
print('ne_tree',ne_tree)

[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!
[nltk_data] Downloading package words to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package words is already up-to-date!


[('Steve', 'NNP'), ('Jobs', 'NNP'), ('was', 'VBD'), ('the', 'DT'), ('CEO', 'NNP'), ('of', 'IN'), ('Apple', 'NNP'), ('Corp.', 'NNP'), ('in', 'IN'), ('California', 'NNP'), ('.', '.')]
ne_tree (S
  (PERSON Steve/NNP)
  (PERSON Jobs/NNP)
  was/VBD
  the/DT
  (ORGANIZATION CEO/NNP)
  of/IN
  (ORGANIZATION Apple/NNP Corp./NNP)
  in/IN
  (GPE California/NNP)
  ./.)


In [69]:
named_entities =[]
for subtree in ne_tree.subtrees():
   if subtree.label() in ['PERSON', 'ORGANIZATION', 'LOCATION']:
      named_entity  = ' '.join(word for word ,tag in subtree.leaves())
      print(named_entity)
      named_entities.append((named_entity,subtree.label()))

print(named_entities)

Steve
Jobs
CEO
Apple Corp.
[('Steve', 'PERSON'), ('Jobs', 'PERSON'), ('CEO', 'ORGANIZATION'), ('Apple Corp.', 'ORGANIZATION')]


In [70]:
for word, tag in subtree.leaves():
    print(word)

California


In [72]:
!pip install textblob

   ---------------------------------------- 0.0/625.0 kB ? eta -:--:--
   ---------------------------------------- 0.0/625.0 kB ? eta -:--:--
   ---------------------------------------- 0.0/625.0 kB ? eta -:--:--
   ---------------- ----------------------- 262.1/625.0 kB ? eta -:--:--
   ---------------- ----------------------- 262.1/625.0 kB ? eta -:--:--
   ------------------------------- ------ 524.3/625.0 kB 621.2 kB/s eta 0:00:01
   -------------------------------------- 625.0/625.0 kB 595.8 kB/s eta 0:00:00



[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [73]:
from textblob import TextBlob
text = "I havv a goood speling!"
corrected_text = TextBlob(text).correct()
print(corrected_text)

I have a good spelling!


In [6]:
paragraph =  """I have three visions for India. In 3000 years of our history, people from all over
               the world have come and invaded us, captured our lands, conquered our minds.
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours.
               Yet we have not done this to any other nation. We have not conquered anyone.
               We have not grabbed their land, their culture,
               their history and tried to enforce our way of life on them.
               Why? Because we respect the freedom of others.That is why my
               first vision is that of freedom. I believe that India got its first vision of
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India
               stands up to the world, no one will respect us. Only strength respects strength. We must be
               strong not only as a military power but also as an economic power. Both must go hand-in-hand.
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life.
               I see four milestones in my career"""

In [2]:
import re
import nltk


nltk.download('punkt')
nltk.download('stopwords')
from nltk.corpus import stopwords

from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [8]:
#cleaning the text
stemmer = PorterStemmer()
lemitizer =WordNetLemmatizer()
sentences=nltk.sent_tokenize(paragraph)
corpus=[]
for i in range(len(sentences)):
   review=re.sub('[^a-zA-Z]', ' ', sentences[i])
   review=review.lower()
   review=review.split()
   review = [lemitizer.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
   review=' '.join(review)
   corpus.append(review)
print(len(corpus))  
corpus 

31


['three vision india',
 'year history people world come invaded u captured land conquered mind',
 'alexander onwards greek turk mogul portuguese british french dutch came looted u took',
 'yet done nation',
 'conquered anyone',
 'grabbed land culture history tried enforce way life',
 '',
 'respect freedom others first vision freedom',
 'believe india got first vision started war independence',
 'freedom must protect nurture build',
 'free one respect u',
 'second vision india development',
 'fifty year developing nation',
 'time see developed nation',
 'among top nation world term gdp',
 'percent growth rate area',
 'poverty level falling',
 'achievement globally recognised today',
 'yet lack self confidence see developed nation self reliant self assured',
 'incorrect',
 'third vision',
 'india must stand world',
 'believe unless india stand world one respect u',
 'strength respect strength',
 'must strong military power also economic power',
 'must go hand hand',
 'good fortune worked

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
x = cv.fit_transform(corpus).toarray()
print(x.shape)
x

(3, 7)


array([[1, 0, 0, 0, 1, 0, 1],
       [0, 0, 1, 1, 0, 1, 0],
       [0, 1, 1, 1, 1, 0, 0]])

In [12]:
v = CountVectorizer()
v.fit(["Thor Hathodawala is looking for ajob"])
v.vocabulary_

{'thor': 5, 'hathodawala': 2, 'is': 3, 'looking': 4, 'for': 1, 'ajob': 0}

In [13]:
v = CountVectorizer(ngram_range=(1,1))
v.fit(["Thor Hathodawala is looking for a job"])
v.vocabulary_

{'thor': 5, 'hathodawala': 1, 'is': 2, 'looking': 4, 'for': 0, 'job': 3}

In [14]:
v = CountVectorizer(ngram_range=(1,2))
v.fit(["Thor Hathodawala is looking for a job"])
v.vocabulary_

{'thor': 9,
 'hathodawala': 2,
 'is': 4,
 'looking': 7,
 'for': 0,
 'job': 6,
 'thor hathodawala': 10,
 'hathodawala is': 3,
 'is looking': 5,
 'looking for': 8,
 'for job': 1}

In [15]:
v = CountVectorizer(ngram_range=(1,3))
v.fit(["Thor Hathodawala is looking for a job"])
v.vocabulary_

{'thor': 12,
 'hathodawala': 2,
 'is': 5,
 'looking': 9,
 'for': 0,
 'job': 8,
 'thor hathodawala': 13,
 'hathodawala is': 3,
 'is looking': 6,
 'looking for': 10,
 'for job': 1,
 'thor hathodawala is': 14,
 'hathodawala is looking': 4,
 'is looking for': 7,
 'looking for job': 11}

In [1]:
corpus = [
    "Thor ate pizza",
    "Loki is tall",
    "Loki is eating pizza"
]

In [2]:
import spacy
nlp = spacy.load("en_core_web_sm")

def preprocess(text):
   doc = nlp(text)
   filtered_tokens =[]
   for token in doc :
      if token.is_stop or token.is_punct:
         continue
      filtered_tokens.append(token.lemma_)
   return " ".join(filtered_tokens)
   

In [3]:
preprocess("Thor ate pizza")


'thor eat pizza'

In [4]:
preprocess("Loki is eating pizza")


'Loki eat pizza'

In [5]:
corpus_processed = [
    preprocess(text) for text in corpus
]
corpus_processed

['thor eat pizza', 'Loki tall', 'Loki eat pizza']

In [8]:
v = CountVectorizer(ngram_range=(1,2))
v.fit(corpus_processed)
v.vocabulary_

{'thor': 7,
 'eat': 0,
 'pizza': 5,
 'thor eat': 8,
 'eat pizza': 1,
 'loki': 2,
 'tall': 6,
 'loki tall': 4,
 'loki eat': 3}

In [9]:
v.transform(["Thor eat pizza"]).toarray()

array([[1, 1, 0, 0, 0, 1, 0, 1, 1]])

In [10]:
v.transform(["Hulk eat pizza"]).toarray()

array([[1, 1, 0, 0, 0, 1, 0, 0, 0]])

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

In [12]:
docs = [
  "The quick brown fox jumps over the lazy dog.",
  "A stitch in time saves nine.",
  "The early bird catches the worm.",
  "Actions speak louder than words.",
]

In [14]:
tfidf = TfidfVectorizer()
tfidf.fit(docs)
tfidf_matrix = tfidf.transform(docs)
print(tfidf_matrix.toarray())

[[0.         0.         0.32467583 0.         0.32467583 0.
  0.32467583 0.         0.32467583 0.32467583 0.         0.
  0.32467583 0.32467583 0.         0.         0.         0.
  0.5119563  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.4472136  0.         0.         0.         0.4472136
  0.         0.         0.4472136  0.         0.4472136  0.
  0.         0.4472136  0.         0.        ]
 [0.         0.39264414 0.         0.39264414 0.         0.39264414
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.6191303  0.         0.         0.39264414]
 [0.4472136  0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.4472136  0.
  0.         0.         0.         0.4472136  0.         0.4472136
  0.         0.         0.4472136  0.        ]]


In [15]:
df_tfidf =pd.DataFrame(tfidf_matrix.toarray(),columns=tfidf.get_feature_names_out())
print(df_tfidf)


    actions      bird     brown   catches       dog     early       fox  \
0  0.000000  0.000000  0.324676  0.000000  0.324676  0.000000  0.324676   
1  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2  0.000000  0.392644  0.000000  0.392644  0.000000  0.392644  0.000000   
3  0.447214  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

         in     jumps      lazy  ...      over     quick     saves     speak  \
0  0.000000  0.324676  0.324676  ...  0.324676  0.324676  0.000000  0.000000   
1  0.447214  0.000000  0.000000  ...  0.000000  0.000000  0.447214  0.000000   
2  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
3  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.447214   

     stitch      than       the      time     words      worm  
0  0.000000  0.000000  0.511956  0.000000  0.000000  0.000000  
1  0.447214  0.000000  0.000000  0.447214  0.000000  0.000000  
2  0.000000  0.000000  0.619130

In [16]:
doc1 = "the quick brown fox"
doc2 = "the lazy dog"
doc3 = "the quick brown cat"

cv=TfidfVectorizer()
x=cv.fit_transform([doc1, doc2, doc3])
print(cv.get_feature_names_out())
print(x.toarray())

['brown' 'cat' 'dog' 'fox' 'lazy' 'quick' 'the']
[[0.4804584  0.         0.         0.63174505 0.         0.4804584
  0.37311881]
 [0.         0.         0.65249088 0.         0.65249088 0.
  0.38537163]
 [0.4804584  0.63174505 0.         0.         0.         0.4804584
  0.37311881]]


In [17]:
cv=TfidfVectorizer(min_df=2)
x=cv.fit_transform([doc1, doc2, doc3])
print(cv.get_feature_names_out())
print(x.toarray())

['brown' 'quick' 'the']
[[0.61980538 0.61980538 0.48133417]
 [0.         0.         1.        ]
 [0.61980538 0.61980538 0.48133417]]


In [18]:
cv=TfidfVectorizer(min_df=2,stop_words='english')
x=cv.fit_transform([doc1, doc2, doc3])
print(cv.get_feature_names_out())
print(x.toarray())

['brown' 'quick']
[[0.70710678 0.70710678]
 [0.         0.        ]
 [0.70710678 0.70710678]]


In [19]:
text=["Hi How are you How are you doing","Hi what's up","Wow that's awesome"]
cv=TfidfVectorizer(max_df=1)
x_traincv=cv.fit_transform(text)
f_n=cv.get_feature_names_out()
print(f_n)
print(x_traincv.toarray())

['are' 'awesome' 'doing' 'how' 'that' 'up' 'what' 'wow' 'you']
[[0.5547002  0.         0.2773501  0.5547002  0.         0.
  0.         0.         0.5547002 ]
 [0.         0.         0.         0.         0.         0.70710678
  0.70710678 0.         0.        ]
 [0.         0.57735027 0.         0.         0.57735027 0.
  0.         0.57735027 0.        ]]


In [21]:
text=["Hi How are you How are you doing","Hi what's up","Wow that's awesome"]
cv=TfidfVectorizer(max_df=1,stop_words='english')
x_traincv=cv.fit_transform(text)
f_n=cv.get_feature_names_out()
print(f_n)
print(x_traincv.toarray())

['awesome' 'doing' 'wow']
[[0.         1.         0.        ]
 [0.         0.         0.        ]
 [0.70710678 0.         0.70710678]]


In [22]:
from tensorflow.keras.preprocessing.text import one_hot

In [23]:
sents=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]
sents

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [24]:
voc_size=10000

In [25]:
onehot_repr =[one_hot(sent,voc_size) for sent in sents]
print(onehot_repr)

[[8083, 5257, 56, 6370], [8083, 5257, 56, 8545], [8083, 631, 56, 1231], [3571, 240, 3836, 8336, 2145], [3571, 240, 3836, 8336, 7033], [1215, 8083, 7536, 56, 2134], [956, 2490, 2829, 8336]]


In [26]:
import numpy as np
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [27]:
sent_len=8
embedded_docs =pad_sequences(onehot_repr,padding='pre',maxlen=sent_len)
print(embedded_docs)

[[   0    0    0    0 8083 5257   56 6370]
 [   0    0    0    0 8083 5257   56 8545]
 [   0    0    0    0 8083  631   56 1231]
 [   0    0    0 3571  240 3836 8336 2145]
 [   0    0    0 3571  240 3836 8336 7033]
 [   0    0    0 1215 8083 7536   56 2134]
 [   0    0    0    0  956 2490 2829 8336]]


In [28]:
dim=10
model =Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_len))
model.build(input_shape=(32,sent_len))
model.compile('adam','mse')
model.summary()

c:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (32, 8, 10)            │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [29]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 598ms/step
[[[-4.5473944e-02  3.4415673e-02 -4.8681013e-03  4.9985293e-02
   -3.3677030e-02 -4.0161502e-02  2.4425771e-02 -2.2954775e-02
   -2.4522174e-02 -1.9988501e-02]
  [-4.5473944e-02  3.4415673e-02 -4.8681013e-03  4.9985293e-02
   -3.3677030e-02 -4.0161502e-02  2.4425771e-02 -2.2954775e-02
   -2.4522174e-02 -1.9988501e-02]
  [-4.5473944e-02  3.4415673e-02 -4.8681013e-03  4.9985293e-02
   -3.3677030e-02 -4.0161502e-02  2.4425771e-02 -2.2954775e-02
   -2.4522174e-02 -1.9988501e-02]
  [-4.5473944e-02  3.4415673e-02 -4.8681013e-03  4.9985293e-02
   -3.3677030e-02 -4.0161502e-02  2.4425771e-02 -2.2954775e-02
   -2.4522174e-02 -1.9988501e-02]
  [ 4.6189833e-02  6.9143996e-03  4.4632647e-02 -1.8239807e-02
    2.5262978e-02 -4.2897429e-02  4.8563648e-02 -4.8207760e-02
   -3.1523980e-02 -1.1482097e-02]
  [-2.0206356e-02 -1.9528642e-03 -1.6913306e-02  8.8165887e-03
   -3.4708846e-02 -4.8625030e-02 -3.5889674e-02  4.3750670e-02
    4.1999493e-02 -1.3644837e-02]
 

In [ ]:
embedded_docs[0]


array([   0,    0,    0,    0, 8083, 5257,   56, 6370], dtype=int32)

In [31]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step
[[-0.04547394  0.03441567 -0.0048681   0.04998529 -0.03367703 -0.0401615
   0.02442577 -0.02295478 -0.02452217 -0.0199885 ]
 [-0.04547394  0.03441567 -0.0048681   0.04998529 -0.03367703 -0.0401615
   0.02442577 -0.02295478 -0.02452217 -0.0199885 ]
 [-0.04547394  0.03441567 -0.0048681   0.04998529 -0.03367703 -0.0401615
   0.02442577 -0.02295478 -0.02452217 -0.0199885 ]
 [-0.04547394  0.03441567 -0.0048681   0.04998529 -0.03367703 -0.0401615
   0.02442577 -0.02295478 -0.02452217 -0.0199885 ]
 [ 0.04618983  0.0069144   0.04463265 -0.01823981  0.02526298 -0.04289743
   0.04856365 -0.04820776 -0.03152398 -0.0114821 ]
 [-0.02020636 -0.00195286 -0.01691331  0.00881659 -0.03470885 -0.04862503
  -0.03588967  0.04375067  0.04199949 -0.01364484]
 [-0.01152851 -0.03529302  0.03443159  0.0222006  -0.03072492  0.02949775
  -0.04614922 -0.03649192  0.0301968   0.00322195]
 [ 0.03293389 -0.02511129  0.02323623 -0.01133122  0.03559282 -0.01452672
   0.04291171 -0

In [32]:
print(model.predict(embedded_docs)[1])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 235ms/step
[[-0.04547394  0.03441567 -0.0048681   0.04998529 -0.03367703 -0.0401615
   0.02442577 -0.02295478 -0.02452217 -0.0199885 ]
 [-0.04547394  0.03441567 -0.0048681   0.04998529 -0.03367703 -0.0401615
   0.02442577 -0.02295478 -0.02452217 -0.0199885 ]
 [-0.04547394  0.03441567 -0.0048681   0.04998529 -0.03367703 -0.0401615
   0.02442577 -0.02295478 -0.02452217 -0.0199885 ]
 [-0.04547394  0.03441567 -0.0048681   0.04998529 -0.03367703 -0.0401615
   0.02442577 -0.02295478 -0.02452217 -0.0199885 ]
 [ 0.04618983  0.0069144   0.04463265 -0.01823981  0.02526298 -0.04289743
   0.04856365 -0.04820776 -0.03152398 -0.0114821 ]
 [-0.02020636 -0.00195286 -0.01691331  0.00881659 -0.03470885 -0.04862503
  -0.03588967  0.04375067  0.04199949 -0.01364484]
 [-0.01152851 -0.03529302  0.03443159  0.0222006  -0.03072492  0.02949775
  -0.04614922 -0.03649192  0.0301968   0.00322195]
 [ 0.01010042  0.01186712 -0.03499613  0.03798466 -0.03036313  0.0084791
  -0.02499219  0.